variables:
  HEROKU_LOGIN: $HEROKU_LOGIN

stages:
  - development

development:
  stage: development
  script:
    - echo "$HEROKU_LOGIN"
    - echo "$CI_JOB_STAGE"
    - echo "https://$HEROKU_LOGIN:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_URL.git"
    # - git remote add heroku https://$HEROKU_LOGIN:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_URL.git
    # - git remote -v
    # - git push -f heroku master
