stages:
  - development

development:
  type: deploy
  stage: development
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_URL.git
    - git push -f heroku master
  only: master
