stages:
  - development

development:
  stage: development
  script:
    - git remote add heroku https://$HEROKU_LOGIN:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_URL.git
    - git remote -v
    - git push -f heroku master
